-- MYSQL KULLANICI ISLEMLERI

CREATE USER 'KULLANCIADI'@'LOCALHOST' IDENTIFIED BY 'SIFRE';
-- SADECE LOCALHOSTA CALISABILIR

CREATE USER 'KULLANCIADI'@'%' IDENTIFIED BY 'SIFRE';

-- HER YERDEN ERISIMI ACMA


SELECT HOST,USER FROM MYSQL.USER;

-- KULLANICILARI GOREBILIRSINIZ
-- OLUSTURGUMUZ KULLANCIYA TUM YETKILERI VERME

GRANT ALL PRIVILEGES ON *.* TO 'KULLANICI_ADI'@'localhost' WITH GRANT OPTION

-- BELIRLI DATABASE YERINDEN YETKI VERME
-- SELECT YEKISI VERELIM

GRANT  SELECT ON DATABASE_ADI.* TO 'KULLANICI_ADI'@'LOCALHOST';
GRANT  SELECT,UPDATE,DROP,CREATE,DELETE ON DATABASE_ADI.* TO 'KULLANICI_ADI'@'LOCALHOST';
GRANT  SELECT,UPDATE,DROP,CREATE,DELETE ON *.* TO 'KULLANICI_ADI'@'LOCALHOST';

-- BELIRLI DATABASE VE TABLOYA YETKI VERME

GRANT  SELECT ON DATABASE_ADI.TABLO_ADI* TO 'KULLANICI_ADI'@'LOCALHOST';


-- ALL PRIVILEGES = 'TUM YETKILERI VERMEK ANLAMINDA'
-- WITH GRANT OPTION ='BASKA KULLANICILARA YETKI VERME YETKI KALDIRMA'
-- SQL CRUD KODLARI..
-- KULLANCI SILME

DROP USER 'KULLANCI_ADI'@'LOCALHOST';VEYA
DROP USER 'KULLANCI_ADI'@'%';

-- KULLANICI YETKILERINI GORME

SHOW GRANTS FOR 'KULLANICI_ADI'@'LOCALHOST';

-- KULLANICI YETKI SILME

REVOKE SELECT ON *.* FROM 'KULLANCI_ADI'@'LOCALHOST';
-- HERHANGI DATABSEDEN HERHANGI TABLODAN YETKI SILME

REVOKE SELECT,UPDATE,DELETE ON DATABASE_ISMI.TABLO_ISMI FROM 'KULLANCI_ADI'@'LOCALHOST';




